name: VktoTG

on:
    push:
jobs:
  VktoTGBot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Install Dependencies
        run: python -m pip install requests   
      - name:  Run App
        run: python vk_chat_to_tg.py 